### ISSUE TITLE
我已经配置了 Webhook 地址，但是没有回调数据响应

### ISSUE THREAD

**Issue by gyp719** [ComPDFKit/compdfkit-api-php#1]
<img width="1475" alt="image" src="https://github.com/ComPDFKit/compdfkit-api-php/assets/30563368/aeac6347-c4fa-42e2-b017-303eadadaf09">

<img width="1260" alt="image" src="https://github.com/ComPDFKit/compdfkit-api-php/assets/30563368/ef4795ae-32bc-4def-bc27-87a1656ede7e">

**Comment by gyp719** [comment]
> 您好 @gyp719 ，非常感谢你的反馈。
> 
> 你设置的webhook地址没有授权我们进行访问。请设置为可公共访问的有效webhook地址。
> 
> 如果有其他问题，请给我们留言，我们会尽快回复。 谢谢~

已经设置了公共访问的有效webhook地址， 依旧没有回调数据返回


`Create a client
    $client = new \ComPDFKit\Client\CPDFClient('public_key_857ceb109aeXXXXX', 'secret_key_1f381XXXXXX');


    $taskInfo = $client->createTask(\ComPDFKit\Constant\CPDFConversion::PDF_TO_TXT);

    $file = $client->addFile(public_path('test.pdf'))->uploadFile($taskInfo['taskId']);

    // Execute Task
    $res = $client->executeTask($taskInfo['taskId']);

// Query TaskInfo
    $taskInfo = $client->getTaskInfo($taskInfo['taskId']);

    dd ($taskInfo);`

<img width="1182" alt="image" src="https://github.com/ComPDFKit/compdfkit-api-php/assets/30563368/3f37eda8-f69e-4867-9283-daf4b675a8d4">

**Comment by gyp719** [comment]
<img width="1361" alt="image" src="https://github.com/ComPDFKit/compdfkit-api-php/assets/30563368/c2a059ae-d7d0-4ac6-a80e-35edb3e6cf83">

没有回调， 是需要使用 这个 密钥令牌 吗 ？ 这个密钥令牌 是在什么情况下使用？ 如何使用？

**Comment by youna12345** [comment]
> > 您好 @gyp719 ，非常感谢你的反馈。
> > 你设置的webhook地址没有授权我们进行访问。请设置为可公共访问的有效webhook地址。
> > 如果有其他问题，请给我们留言，我们会尽快回复。 谢谢~
> 
> 已经设置了公共访问的有效webhook地址， 依旧没有回调数据返回
> 
> `Create a client $client = new \ComPDFKit\Client\CPDFClient('public_key_857ceb109aeXXXXX', 'secret_key_1f381XXXXXX');
> 
> ```
> $taskInfo = $client->createTask(\ComPDFKit\Constant\CPDFConversion::PDF_TO_TXT);
> 
> $file = $client->addFile(public_path('test.pdf'))->uploadFile($taskInfo['taskId']);
> 
> // Execute Task
> $res = $client->executeTask($taskInfo['taskId']);
> ```
> 
> // Query TaskInfo $taskInfo = $client->getTaskInfo($taskInfo['taskId']);
> 
> ```
> dd ($taskInfo);`
> ```
> 
> <img alt="image" width="1182" src="https://private-user-images.githubusercontent.com/30563368/339608209-3f37eda8-f69e-4867-9283-daf4b675a8d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDczNjMsIm5iZiI6MTcxODM0NzA2MywicGF0aCI6Ii8zMDU2MzM2OC8zMzk2MDgyMDktM2YzN2VkYTgtZjY5ZS00ODY3LTkyODMtZGFmNGI2NzVhOGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA2Mzc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZGFlMjk2MTQyYzE4ZTI3ZWI2YTI4NDYzZTRhNzIzZDFkMmNhZTg1YzlhYTk4YTZmZTQ1ZDIzNWFhNjA3MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dspy_2lWSlBGq6f9FYcoNab8n-OAVK2gOsBbb7ZmIoM">

您好 @gyp719 ，非常感谢你的反馈。

我们已经修复了这个问题，可以再测试一下。

如果有其他问题，请给我们留言，我们会尽快回复。
谢谢~

**Comment by gyp719** [comment]
好的，已经有回调数据了。 感谢您的解决。
![Uploading image.png…]()
